In [16]:
!pip install -r ../requirements.txt

  Using cached pandas-2.2.3-cp310-cp310-macosx_11_0_arm64.whl.metadata (89 kB)
  Using cached pytz-2024.2-py2.py3-none-any.whl.metadata (22 kB)
  Using cached tzdata-2024.2-py2.py3-none-any.whl.metadata (1.4 kB)
Using cached pandas-2.2.3-cp310-cp310-macosx_11_0_arm64.whl (11.3 MB)
Using cached pytz-2024.2-py2.py3-none-any.whl (508 kB)
Using cached tzdata-2024.2-py2.py3-none-any.whl (346 kB)


In [1]:
%load_ext autoreload
%autoreload 2

In [679]:
import numpy as np
import pandas as pd
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.model_selection import train_test_split


from src.components import data_ingestion
from src.components import data_transformation
from src.components import data_loading
from src import utils

In [26]:
data = np.load("../data/raw_data/npz_files_10377.npz", allow_pickle=True)

In [658]:
dataset = data_ingestion.DataIngestion().initiate_data_ingestion()

/Users/jayparekh/Documents/projects/musidict/src/components/data_ingestion.py:58: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  


In [665]:
_, transformed_data = data_transformation.DataTransformation().initiate_data_transformation()

/Users/jayparekh/Documents/projects/musidict/src/components/data_ingestion.py:58: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  
/Users/jayparekh/Documents/projects/musidict/src/components/data_transformation.py:47: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  df_data = np.array(df_data)


In [671]:
torch.tensor(transformed_data[:, -3:].astype(float))

tensor([[0., 1., 0.],
        [0., 0., 1.],
        [0., 0., 1.],
        [0., 0., 1.],
        [0., 0., 1.],
        [0., 0., 1.],
        [1., 0., 0.],
        [0., 0., 1.]], dtype=torch.float64)

In [659]:
dataset["genre"]

0    38
1    15
2    38
3    15
4    15
5    15
6    21
7    21
Name: genre, dtype: object

In [662]:
z = np.column_stack((transformed_data, dataset["genre"].values))

In [664]:
z[:,14]

array([38, 15, 38, 15, 15, 15, 21, 21], dtype=object)

In [565]:
import numpy as np
import torch

# Example numpy array with dtype=object and some 2D arrays
# data = np.array([
#     [1, 2, 3, np.array([[1, 2], [3, 4]])],
#     [4, 5, 6, np.array([[5, 6], [7, 8]])],
#     [7, 8, 9, np.array([[9, 10], [11, 12]])]
# ], dtype=object)

# Step 1: Flatten 2D arrays into 1D arrays
flattened_data = []
for row in transformed_data:
    flattened_row = []
    for value in row:
        if isinstance(value, np.ndarray):  # Check if value is a 2D array
            flattened_row.extend(value.flatten())  # Flatten the 2D array and add to list
        else:
            flattened_row.append(value)  # Keep the scalar as is
    flattened_data.append(flattened_row)

# Step 2: Convert the flattened data to a numpy array with a numeric dtype
flattened_data = np.array(flattened_data, dtype=np.float32)

# Step 3: Convert the numpy array to a PyTorch tensor
tensor_data = torch.tensor(flattened_data)

print(tensor_data)


tensor([[-1.0000,  1.5103,  0.1941,  ...,  0.0000,  1.0000,  0.0000],
        [-1.0000, -0.3382,  2.6844,  ...,  0.0000,  0.0000,  1.0000],
        [-1.0000,  1.5103,  0.1941,  ...,  0.0000,  0.0000,  1.0000],
        ...,
        [ 1.0000, -1.0849,  1.2610,  ...,  0.0000,  0.0000,  1.0000],
        [ 1.0000, -1.0482, -0.0611,  ...,  1.0000,  0.0000,  0.0000],
        [ 1.0000,  0.6044,  6.8222,  ...,  0.0000,  0.0000,  1.0000]])


In [603]:
a = np.random.randn(8, 13, 937)  # Example shape (8 samples, 128, 937)
b = np.random.randn(8, 13, 937)
c = np.random.randn(8, 13, 937)

In [592]:
np.array(["hi"]).reshape(-1, 1)

array([['hi']], dtype='<U2')

In [604]:
row = np.array([c, a, b])
rows = np.array([row, row])

In [598]:
rows[:,2]

array([array([[[-9.32591226e-01,  8.03701467e-02,  6.83964362e-01, ...,
                -5.72991170e-01,  4.31724471e-01,  9.11943202e-02],
               [ 1.89460574e+00, -3.10259827e-01, -1.64953152e+00, ...,
                 1.28958543e+00,  7.20388327e-02, -8.21509916e-01],
               [-1.59077917e-01, -3.73181385e-01, -8.22829599e-01, ...,
                 1.50659414e-01,  4.79185055e-01, -1.94044324e-01],
               ...,
               [-3.59585621e-01, -1.40083098e-01, -2.44647316e-01, ...,
                 1.23960382e-03,  1.13018949e+00, -1.68995936e+00],
               [ 1.29611184e+00, -1.06634314e+00,  1.11686303e+00, ...,
                -1.08359967e+00, -2.12222040e-01,  6.89329905e-01],
               [-6.20692472e-01, -8.14532955e-01,  1.13668648e+00, ...,
                 1.39341856e+00, -8.32018175e-01,  6.81734502e-01]],

              [[ 6.12174544e-01,  4.12701918e-01, -2.59775668e-01, ...,
                 1.03453083e+00,  8.95334709e-01,  3.21396759e-01]

In [615]:
features = {
    'mel_spectrogram': np.random.randn(10, 128, 937),
    'mfccs': np.random.randn(10, 13, 937),
    'chroma': np.random.randn(10, 12, 937),
    'spectral_contrast': np.random.randn(10, 7, 937),
    'zcr': np.random.randn(10, 1, 937),
    'spectral_centroid': np.random.randn(10, 1, 937),
    'spectral_bandwidth': np.random.randn(10, 1, 937),
    'rms_energy': np.random.randn(10, 1, 937),
    'tonnetz': np.random.randn(10, 6, 937),
}

# Bit rate and duration as scalar values
bit_rate = np.random.rand(10)
duration = np.random.rand(10)


In [616]:


# Sample categorical data
genres = ['pop', 'rock', 'jazz', 'classical'] * 2 + ['pop', 'classical']  # 1000 samples
song_success = ['hit', 'flop', "can't say"] * 3 + ['hit']  # 1000 samples

# One-hot encode genres
genre_encoder = OneHotEncoder(sparse=False)
genres_encoded = genre_encoder.fit_transform(np.array(genres).reshape(-1, 1))  # Shape: (1000, num_genres)

# One-hot encode song success
success_encoder = OneHotEncoder(sparse=False)
success_encoded = success_encoder.fit_transform(np.array(song_success).reshape(-1, 1))  # Shape: (1000, 3)


/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py:808: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py:808: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


In [617]:
scaler_2d = StandardScaler()
scaler_scalar = StandardScaler()

# Example standardization for each 2D time-series feature
features_scaled = {}
for feature_name, feature_data in features.items():
    # Flatten, scale, then reshape
    flat_feature = feature_data.reshape(-1, feature_data.shape[-1])  # Shape: (N*D, T)
    scaled_flat_feature = scaler_2d.fit_transform(flat_feature)
    features_scaled[feature_name] = scaled_flat_feature.reshape(feature_data.shape)

# Example scaling for scalar features
bit_rate_scaled = scaler_scalar.fit_transform(bit_rate.reshape(-1, 1)).flatten()
duration_scaled = scaler_scalar.fit_transform(duration.reshape(-1, 1)).flatten()

In [618]:
from torch.utils.data import DataLoader, Dataset

class MusicDataset(Dataset):
    def __init__(self, scaled_features, genre_one_hot, bit_rate_scaled, duration_scaled, targets_one_hot):
        self.features = scaled_features
        self.genre_one_hot = genre_one_hot.astype(np.float32)
        self.bit_rate = bit_rate_scaled.astype(np.float32)
        self.duration = duration_scaled.astype(np.float32)
        self.targets = targets_one_hot.astype(np.float32)

    def __len__(self):
        return len(self.targets)

    def __getitem__(self, idx):
        return {
            'mel_spectrogram': torch.tensor(self.features['mel_spectrogram'][idx], dtype=torch.float32),
            'mfccs': torch.tensor(self.features['mfccs'][idx], dtype=torch.float32),
            'chroma': torch.tensor(self.features['chroma'][idx], dtype=torch.float32),
            'spectral_contrast': torch.tensor(self.features['spectral_contrast'][idx], dtype=torch.float32),
            'zcr': torch.tensor(self.features['zcr'][idx], dtype=torch.float32),
            'spectral_centroid': torch.tensor(self.features['spectral_centroid'][idx], dtype=torch.float32),
            'spectral_bandwidth': torch.tensor(self.features['spectral_bandwidth'][idx], dtype=torch.float32),
            'rms_energy': torch.tensor(self.features['rms_energy'][idx], dtype=torch.float32),
            'tonnetz': torch.tensor(self.features['tonnetz'][idx], dtype=torch.float32),
            'bit_rate': torch.tensor(self.bit_rate[idx], dtype=torch.float32),
            'duration': torch.tensor(self.duration[idx], dtype=torch.float32),
            'genre': torch.tensor(self.genre_one_hot[idx], dtype=torch.float32),
            'target': torch.tensor(self.targets[idx], dtype=torch.float32),
        }


In [619]:
# Create dataset
dataset = MusicDataset(features_scaled, genres_encoded, bit_rate_scaled, duration_scaled, success_encoded)

# DataLoader with batch size
dataloader = DataLoader(dataset, batch_size=32, shuffle=True, num_workers=4)


In [620]:
for b in dataloader:
    print(b)
    break

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
AttributeError: Can't get attribute 'MusicDataset' on <module '__main__' (built-in)>


KeyboardInterrupt: 

In [614]:
b.shape

(8, 13, 937)

In [624]:
row = np.array([[0], [2 ,3 ]], dtype=np.float32)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [622]:
rows = np.array([row, row])

In [623]:
rows

array([[list([0]), list([2, 3])],
       [list([0]), list([2, 3])]], dtype=object)

In [632]:
torch.tensor(transformed_data[:, 1])

TypeError: can't convert np.ndarray of type numpy.object_. The only supported types are: float64, float32, float16, complex64, complex128, int64, int32, int16, int8, uint64, uint32, uint16, uint8, and bool.

In [643]:
first = torch.tensor(transformed_data[:, 1].astype(float))

In [644]:
second = torch.tensor(np.stack(transformed_data[:, 2]))

In [650]:
scalar_tensor_expanded = first.view(-1, 1, 1)  # Make each scalar a 1x1 matrix
first = scalar_tensor_expanded.expand(-1, *second.shape[1:])

In [646]:
second.shape

torch.Size([8, 128, 937])

In [652]:
result = torch.cat((first, second), dim=1)

In [653]:
result.shape

torch.Size([8, 256, 937])

In [654]:
result[0]

tensor([[ 1.5103,  1.5103,  1.5103,  ...,  1.5103,  1.5103,  1.5103],
        [ 1.5103,  1.5103,  1.5103,  ...,  1.5103,  1.5103,  1.5103],
        [ 1.5103,  1.5103,  1.5103,  ...,  1.5103,  1.5103,  1.5103],
        ...,
        [-0.3266, -0.3103, -0.2810,  ..., -0.3151, -0.3266, -0.3038],
        [-0.3266, -0.3103, -0.2810,  ..., -0.3151, -0.3266, -0.3038],
        [-0.3266, -0.3103, -0.2810,  ..., -0.3151, -0.3266, -0.3038]],
       dtype=torch.float64)

In [672]:
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
import numpy as np

# Sample DataLoader for Music Dataset (Assumes you already have the data loaded)
class MusicDataset(Dataset):
    def __init__(self, features, targets, genres, bit_rate, duration):
        self.features = features  # Dictionary with all feature arrays
        self.targets = targets    # One-hot encoded target
        self.genres = genres      # Indices for genres
        self.bit_rate = bit_rate
        self.duration = duration

    def __getitem__(self, idx):
        mel_spectrogram = torch.tensor(self.features['mel_spectrogram'][idx], dtype=torch.float32)
        mfccs = torch.tensor(self.features['mfccs'][idx], dtype=torch.float32)
        chroma = torch.tensor(self.features['chroma'][idx], dtype=torch.float32)
        spectral_contrast = torch.tensor(self.features['spectral_contrast'][idx], dtype=torch.float32)
        zcr = torch.tensor(self.features['zcr'][idx], dtype=torch.float32)
        spectral_centroid = torch.tensor(self.features['spectral_centroid'][idx], dtype=torch.float32)
        spectral_bandwidth = torch.tensor(self.features['spectral_bandwidth'][idx], dtype=torch.float32)
        rms_energy = torch.tensor(self.features['rms_energy'][idx], dtype=torch.float32)
        tonnetz = torch.tensor(self.features['tonnetz'][idx], dtype=torch.float32)

        # Scalar features
        bit_rate = torch.tensor(self.bit_rate[idx], dtype=torch.float32).unsqueeze(0)
        duration = torch.tensor(self.duration[idx], dtype=torch.float32).unsqueeze(0)

        # Categorical features (genre as an index)
        genre = torch.tensor(self.genres[idx], dtype=torch.long)
        target = torch.tensor(self.targets[idx], dtype=torch.float32)  # One-hot encoded target

        return {
            'mel_spectrogram': mel_spectrogram,
            'mfccs': mfccs,
            'chroma': chroma,
            'spectral_contrast': spectral_contrast,
            'zcr': zcr,
            'spectral_centroid': spectral_centroid,
            'spectral_bandwidth': spectral_bandwidth,
            'rms_energy': rms_energy,
            'tonnetz': tonnetz,
            'bit_rate': bit_rate,
            'duration': duration,
            'genre': genre,
            'target': target
        }

    def __len__(self):
        return len(self.features['mel_spectrogram'])

# Define the model for predicting song success
class MusicSuccessPredictor(nn.Module):
    def __init__(self, genre_size=10, genre_embedding_dim=4):
        super(MusicSuccessPredictor, self).__init__()

        # Embedding for genres (10 genres, embedding dim 4)
        self.genre_embedding = nn.Embedding(genre_size, genre_embedding_dim)

        # Convolutional layers for mel_spectrogram
        self.conv_mel = nn.Sequential(
            nn.Conv2d(1, 16, kernel_size=(3, 3), stride=(1, 1), padding=1),
            nn.ReLU(),
            nn.MaxPool2d((2, 2))
        )

        # Linear layers for scalar features (bit_rate, duration, and genre embedding)
        self.scalar_fc = nn.Linear(2 + genre_embedding_dim, 16)  # bit_rate + duration + genre embedding

        # Fully connected layers for output
        self.fc1 = nn.Linear(16 + 16, 64)  # Combine features from the CNN and scalar features
        self.fc2 = nn.Linear(64, 3)  # 3 categories for output (hit, flop, can't say)
        self.softmax = nn.Softmax(dim=1)  # Softmax activation for classification

    def forward(self, mel_spectrogram, mfccs, chroma, spectral_contrast, zcr, spectral_centroid,
                spectral_bandwidth, rms_energy, tonnetz, bit_rate, duration, genre):

        # Embedding for genre
        genre_embedding = self.genre_embedding(genre)  # Shape: (batch_size, genre_embedding_dim)

        # Process mel_spectrogram with CNN
        mel_spectrogram = mel_spectrogram.unsqueeze(1)  # Add channel dimension for Conv2d
        mel_features = self.conv_mel(mel_spectrogram)
        mel_features = torch.flatten(mel_features, start_dim=1)

        # Combine scalar features with genre embedding
        scalar_features = torch.cat([bit_rate, duration, genre_embedding], dim=1)
        scalar_features = self.scalar_fc(scalar_features)

        # Combine CNN features and scalar features, pass through fully connected layers
        combined_features = torch.cat([mel_features, scalar_features], dim=1)
        x = self.fc1(combined_features)
        x = torch.relu(x)  # Apply activation function
        output = self.fc2(x)  # Output layer with 3 categories

        # Softmax for classification
        output = self.softmax(output)

        return output

# Data preparation
# Assuming you have features and labels as numpy arrays and one-hot encoded target
features = {
    'mel_spectrogram': np.random.rand(1000, 128, 937),  # Example shape: (num_samples, 128, 937)
    'mfccs': np.random.rand(1000, 13, 937),
    'chroma': np.random.rand(1000, 12, 937),
    'spectral_contrast': np.random.rand(1000, 7, 937),
    'zcr': np.random.rand(1000, 1, 937),
    'spectral_centroid': np.random.rand(1000, 1, 937),
    'spectral_bandwidth': np.random.rand(1000, 1, 937),
    'rms_energy': np.random.rand(1000, 1, 937),
    'tonnetz': np.random.rand(1000, 6, 937)
}
bit_rate = np.random.rand(1000)  # Scalar feature
duration = np.random.rand(1000)  # Scalar feature
genres = np.random.randint(0, 10, 1000)  # Integer indices for genres (10 genres)
targets = np.random.randint(0, 3, 1000)  # Example target labels: 0=hit, 1=flop, 2=can't say

# One-hot encoding the target
targets_onehot = np.eye(3)[targets]

# Create Dataset and DataLoader
dataset = MusicDataset(features, targets_onehot, genres, bit_rate, duration)
dataloader = DataLoader(dataset, batch_size=32, shuffle=True)

# # Model initialization
# model = MusicSuccessPredictor()

# # Loss function and optimizer
# loss_fn = nn.CrossEntropyLoss()  # Cross-entropy loss for multi-class classification
# optimizer = optim.Adam(model.parameters(), lr=0.001)

# # Training Loop
# num_epochs = 10
# for epoch in range(num_epochs):
#     for batch in dataloader:
#         mel_spectrogram = batch['mel_spectrogram']
#         mfccs = batch['mfccs']
#         chroma = batch['chroma']
#         spectral_contrast = batch['spectral_contrast']
#         zcr = batch['zcr']
#         spectral_centroid = batch['spectral_centroid']
#         spectral_bandwidth = batch['spectral_bandwidth']
#         rms_energy = batch['rms_energy']
#         tonnetz = batch['tonnetz']
#         bit_rate = batch['bit_rate']
#         duration = batch['duration']
#         genre = batch['genre']
#         target = batch['target']  # One-hot encoded target

#         # Zero gradients
#         optimizer.zero_grad()

#         # Forward pass
#         outputs = model(mel_spectrogram, mfccs, chroma, spectral_contrast, zcr,
#                         spectral_centroid, spectral_bandwidth, rms_energy, tonnetz,
#                         bit_rate, duration, genre)

#         # Loss calculation
#         loss = loss_fn(outputs, torch.max(target, 1)[1])  # Cross-entropy loss with one-hot target

#         # Backward pass and optimization
#         loss.backward()
#         optimizer.step()

#     print(f"Epoch {epoch+1}/{num_epochs}, Loss: {loss.item()}")

# # Save the model after training
# torch.save(model.state_dict(), 'music_success_predictor.pth')


In [673]:
for d in dataloader:
    break

In [677]:
d["mel_spectrogram"].shape

torch.Size([32, 128, 937])

In [699]:
result = utils.convert_dataset_into_tensor_dict(transformed_data)

In [ ]:
torch.tensor(np.stack(transformed_data[:, 1]) ,dtype=torch.flo)

tensor([-1., -1., -1.,  1., -1.,  1.,  1.,  1.], dtype=torch.float64)

In [697]:
result['mel_spectrogram'].shape

torch.Size([8, 128, 937])

In [701]:
result["success"].shape

torch.Size([8, 3])

In [702]:
targets = np.random.randint(0, 3, 1000)  # Example target labels: 0=hit, 1=flop, 2=can't say


In [704]:
targets.shape

(1000,)

In [705]:
targets_onehot = np.eye(3)[targets]

In [708]:
torch.tensor(targets_onehot).shape

torch.Size([1000, 3])

In [711]:
a = data_loading.DataModule(2)

In [712]:
a.load_and_split_data()

In [713]:
t = a.train_dataloader()

In [714]:
for i in t:
    break

Seed set to 7
Seed set to 7
Seed set to 7
/Users/jayparekh/Documents/projects/musidict/src/components/data_loading.py:24: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  mel_spectrogram = torch.tensor(self.features['mel_spectrogram'][idx], dtype=torch.float32)
/Users/jayparekh/Documents/projects/musidict/src/components/data_loading.py:24: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  mel_spectrogram = torch.tensor(self.features['mel_spectrogram'][idx], dtype=torch.float32)
/Users/jayparekh/Documents/projects/musidict/src/components/data_loading.py:24: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requir

In [719]:
i['mel_spectrogram'].shape

torch.Size([2, 128, 937])

In [720]:
from src.components import model_trainer

In [721]:
import torch

# Create a 2x3 tensor
input_tensor = torch.tensor([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])

# Apply softmax along dim=0 (rows)
softmax_dim0 = torch.softmax(input_tensor, dim=0)
print("Softmax along dim=0:\n", softmax_dim0)

# Apply softmax along dim=1 (columns)
softmax_dim1 = torch.softmax(input_tensor, dim=1)
print("Softmax along dim=1:\n", softmax_dim1)


Softmax along dim=0:
 tensor([[0.0474, 0.0474, 0.0474],
        [0.9526, 0.9526, 0.9526]])
Softmax along dim=1:
 tensor([[0.0900, 0.2447, 0.6652],
        [0.0900, 0.2447, 0.6652]])


In [724]:
data_loader_obj = data_loading.DataModule(batch_size=2)
# data_ingestion.DataIngestion().initiate_data_ingestion()
train_loader = data_loader_obj.train_dataloader()
val_loader = data_loader_obj.val_dataloader()

INFO: Seed set to 7


In [725]:
for vb in val_loader:
    break

Seed set to 7
Seed set to 7
Seed set to 7
/Users/jayparekh/Documents/projects/musidict/src/components/data_loading.py:24: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  mel_spectrogram = torch.tensor(self.features['mel_spectrogram'][idx], dtype=torch.float32)
/Users/jayparekh/Documents/projects/musidict/src/components/data_loading.py:25: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  mfccs = torch.tensor(self.features['mfccs'][idx], dtype=torch.float32)
/Users/jayparekh/Documents/projects/musidict/src/components/data_loading.py:26: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rath

In [726]:
vb["bit_rate"]
# print(batch['bit_rate'].float(),   # Scalar (batch_size, 1)
#                 batch['duration'].float(),   # Scalar (batch_size, 1)
#                 batch['genre'].float())

INFO: Seed set to 7


tensor([[-1.]])

In [727]:
vb["duration"]

tensor([[-0.3382]])

In [728]:
vb["genre"]

tensor([15])

In [729]:
t_dataset = np.load("/Users/jayparekh/Documents/projects/musidict/data/transformed_data/transformed_dataset.npy", allow_pickle=True)


In [737]:
t_dataset[:, 0].shape

(8,)

In [738]:
t_dataset[:, 2].shape

(8,)

In [776]:
t_dash = utils.convert_dataset_into_tensor_dict(t_dataset)

In [740]:
t_dash["genre"].shape

torch.Size([8])

In [744]:
t_dash["duration"].shape

torch.Size([8])

In [742]:
t_dash

{'genre': tensor([38., 15., 38., 15., 15., 15., 21., 21.]),
 'bit_rate': tensor([-1., -1., -1.,  1., -1.,  1.,  1.,  1.]),
 'duration': tensor([ 1.5103, -0.3382,  1.5103, -0.6687, -0.4851, -1.0849, -1.0482,  0.6044]),
 'mel_spectrogram': tensor([[[ 1.9408e-01, -1.4363e-01,  2.7325e-01,  ..., -1.3466e-01,
           -1.4838e-01,  4.6354e-02],
          [ 1.7389e+00,  3.8034e-01,  1.2502e+00,  ...,  4.4472e-02,
            8.9517e-02,  5.7383e-03],
          [ 4.7102e+00,  8.5159e+00,  9.0111e+00,  ..., -7.5800e-02,
            3.8589e-01,  1.7527e+00],
          ...,
          [-3.2661e-01, -3.1028e-01, -2.8101e-01,  ..., -3.1510e-01,
           -3.2657e-01, -3.0383e-01],
          [-3.2661e-01, -3.1028e-01, -2.8101e-01,  ..., -3.1510e-01,
           -3.2657e-01, -3.0382e-01],
          [-3.2661e-01, -3.1028e-01, -2.8101e-01,  ..., -3.1510e-01,
           -3.2657e-01, -3.0382e-01]],
 
         [[ 2.6844e+00,  4.5670e+00,  1.2024e+00,  ...,  1.0988e+01,
            1.0826e+01,  1.0940e+0

In [746]:
torch.tensor(t_dash["bit_rate"], dtype=torch.float32).unsqueeze(0)

/var/folders/bl/v1vnq6z91qzg_fw0hf90bj0r0000gn/T/ipykernel_84464/3329446056.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  torch.tensor(t_dash["bit_rate"], dtype=torch.float32).unsqueeze(0)


tensor([[-1., -1., -1.,  1., -1.,  1.,  1.,  1.]])

In [747]:
t_dash["bit_rate"]

tensor([-1., -1., -1.,  1., -1.,  1.,  1.,  1.])

In [790]:
import lightning as L
L.seed_everything(7, workers=True)
from lightning.pytorch.callbacks import EarlyStopping, LearningRateMonitor, ModelCheckpoint
from src.components import model_trainer

batch_size = 2
criterion = nn.CrossEntropyLoss()
learning_rate = 0.001
dropout_prob = 0.3
lr_logger = LearningRateMonitor()
early_stopping = EarlyStopping('val_loss_mean', mode='min', patience=10)
model_checkpoint = ModelCheckpoint(dirpath="../artifacts/MODELS",save_last=True, save_top_k=3, monitor="val_loss_mean")
epochs = 10
data_loader_obj = data_loading.DataModule(batch_size=batch_size)
# data_ingestion.DataIngestion().initiate_data_ingestion()
train_loader = data_loader_obj.train_dataloader()
val_loader = data_loader_obj.val_dataloader()

lightning_model = model_trainer.MusicSuccessPredictor(loss_fn=criterion, learning_rate=learning_rate, dropout_prob=dropout_prob)

trainer = L.Trainer(max_epochs=epochs, callbacks=[lr_logger, early_stopping, model_checkpoint])

trainer.fit(lightning_model, train_loader, val_loader)

INFO: Seed set to 7
INFO: Seed set to 7
INFO: GPU available: True (mps), used: True
INFO: TPU available: False, using: 0 TPU cores
INFO: HPU available: False, using: 0 HPUs
INFO: 
   | Name                      | Type             | Params | Mode 
------------------------------------------------------------------------
0  | loss_fn                   | CrossEntropyLoss | 0      | train
1  | mel_conv                  | Sequential       | 4.8 K  | train
2  | mfcc_conv                 | Sequential       | 4.8 K  | train
3  | chroma_conv               | Sequential       | 4.8 K  | train
4  | spectral_contrast_conv    | Sequential       | 4.8 K  | train
5  | tonnetz_conv              | Sequential       | 4.8 K  | train
6  | zcr_branch                | Sequential       | 32     | train
7  | spectral_centroid_branch  | Sequential       | 32     | train
8  | spectral_bandwidth_branch | Sequential       | 32     | train
9  | rms_energy_branch         | Sequential       | 32     | train
10 | scala

Sanity Checking: |          | 0/? [00:00<?, ?it/s]

Seed set to 7
Seed set to 7
Seed set to 7
/Users/jayparekh/Documents/projects/musidict/src/components/data_loading.py:24: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  mel_spectrogram = torch.tensor(self.features['mel_spectrogram'][idx], dtype=torch.float32).unsqueeze(0)
/Users/jayparekh/Documents/projects/musidict/src/components/data_loading.py:24: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  mel_spectrogram = torch.tensor(self.features['mel_spectrogram'][idx], dtype=torch.float32).unsqueeze(0)
/Users/jayparekh/Documents/projects/musidict/src/components/data_loading.py:25: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTens

in forward torch.Size([2, 1, 128, 937])
in forward torch.Size([2, 3])
in forward torch.Size([1, 1, 128, 937])
in forward torch.Size([1, 3])
val_loss_mean 1.010545253753662


/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/lightning/pytorch/trainer/connectors/data_connector.py:419: Consider setting `persistent_workers=True` in 'train_dataloader' to speed up the dataloader worker initialization.
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/lightning/pytorch/loops/fit_loop.py:298: The number of training batches (1) is smaller than the logging interval Trainer(log_every_n_steps=50). Set a lower value for log_every_n_steps if you want to see logs for the training epoch.


Training: |          | 0/? [00:00<?, ?it/s]

Seed set to 7
Seed set to 7
Seed set to 7
/Users/jayparekh/Documents/projects/musidict/src/components/data_loading.py:24: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  mel_spectrogram = torch.tensor(self.features['mel_spectrogram'][idx], dtype=torch.float32).unsqueeze(0)
/Users/jayparekh/Documents/projects/musidict/src/components/data_loading.py:25: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  mfccs = torch.tensor(self.features['mfccs'][idx], dtype=torch.float32).unsqueeze(0)
/Users/jayparekh/Documents/projects/musidict/src/components/data_loading.py:26: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().

in forward torch.Size([1, 1, 128, 937])
in forward torch.Size([1, 3])


Validation: |          | 0/? [00:00<?, ?it/s]

Seed set to 7
Seed set to 7
/Users/jayparekh/Documents/projects/musidict/src/components/data_loading.py:24: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  mel_spectrogram = torch.tensor(self.features['mel_spectrogram'][idx], dtype=torch.float32).unsqueeze(0)
/Users/jayparekh/Documents/projects/musidict/src/components/data_loading.py:25: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  mfccs = torch.tensor(self.features['mfccs'][idx], dtype=torch.float32).unsqueeze(0)
/Users/jayparekh/Documents/projects/musidict/src/components/data_loading.py:26: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_

in forward torch.Size([2, 1, 128, 937])
in forward torch.Size([2, 3])
in forward torch.Size([1, 1, 128, 937])
in forward torch.Size([1, 3])
val_loss_mean 1.0407702922821045
train_loss_mean 1.1472406387329102


Seed set to 7
Seed set to 7
Seed set to 7
/Users/jayparekh/Documents/projects/musidict/src/components/data_loading.py:24: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  mel_spectrogram = torch.tensor(self.features['mel_spectrogram'][idx], dtype=torch.float32).unsqueeze(0)
/Users/jayparekh/Documents/projects/musidict/src/components/data_loading.py:25: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  mfccs = torch.tensor(self.features['mfccs'][idx], dtype=torch.float32).unsqueeze(0)
/Users/jayparekh/Documents/projects/musidict/src/components/data_loading.py:26: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().

in forward torch.Size([1, 1, 128, 937])
in forward torch.Size([1, 3])


Validation: |          | 0/? [00:00<?, ?it/s]

Seed set to 7
Seed set to 7
/Users/jayparekh/Documents/projects/musidict/src/components/data_loading.py:24: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  mel_spectrogram = torch.tensor(self.features['mel_spectrogram'][idx], dtype=torch.float32).unsqueeze(0)
/Users/jayparekh/Documents/projects/musidict/src/components/data_loading.py:25: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  mfccs = torch.tensor(self.features['mfccs'][idx], dtype=torch.float32).unsqueeze(0)
/Users/jayparekh/Documents/projects/musidict/src/components/data_loading.py:26: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_

in forward torch.Size([2, 1, 128, 937])
in forward torch.Size([2, 3])
in forward torch.Size([1, 1, 128, 937])
in forward torch.Size([1, 3])
val_loss_mean 1.0717723369598389
train_loss_mean 1.1190285682678223


Seed set to 7
Seed set to 7
Seed set to 7
/Users/jayparekh/Documents/projects/musidict/src/components/data_loading.py:24: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  mel_spectrogram = torch.tensor(self.features['mel_spectrogram'][idx], dtype=torch.float32).unsqueeze(0)
/Users/jayparekh/Documents/projects/musidict/src/components/data_loading.py:25: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  mfccs = torch.tensor(self.features['mfccs'][idx], dtype=torch.float32).unsqueeze(0)
/Users/jayparekh/Documents/projects/musidict/src/components/data_loading.py:26: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().

in forward torch.Size([1, 1, 128, 937])
in forward torch.Size([1, 3])


Validation: |          | 0/? [00:00<?, ?it/s]

Seed set to 7
Seed set to 7
/Users/jayparekh/Documents/projects/musidict/src/components/data_loading.py:24: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  mel_spectrogram = torch.tensor(self.features['mel_spectrogram'][idx], dtype=torch.float32).unsqueeze(0)
/Users/jayparekh/Documents/projects/musidict/src/components/data_loading.py:25: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  mfccs = torch.tensor(self.features['mfccs'][idx], dtype=torch.float32).unsqueeze(0)
/Users/jayparekh/Documents/projects/musidict/src/components/data_loading.py:26: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_

in forward torch.Size([2, 1, 128, 937])
in forward torch.Size([2, 3])
in forward torch.Size([1, 1, 128, 937])
in forward torch.Size([1, 3])
val_loss_mean 1.1068451404571533
train_loss_mean 1.055660605430603


Seed set to 7
Seed set to 7
Seed set to 7
/Users/jayparekh/Documents/projects/musidict/src/components/data_loading.py:24: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  mel_spectrogram = torch.tensor(self.features['mel_spectrogram'][idx], dtype=torch.float32).unsqueeze(0)
/Users/jayparekh/Documents/projects/musidict/src/components/data_loading.py:25: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  mfccs = torch.tensor(self.features['mfccs'][idx], dtype=torch.float32).unsqueeze(0)
/Users/jayparekh/Documents/projects/musidict/src/components/data_loading.py:26: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().

in forward torch.Size([1, 1, 128, 937])
in forward torch.Size([1, 3])


Validation: |          | 0/? [00:00<?, ?it/s]

Seed set to 7
/Users/jayparekh/Documents/projects/musidict/src/components/data_loading.py:24: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  mel_spectrogram = torch.tensor(self.features['mel_spectrogram'][idx], dtype=torch.float32).unsqueeze(0)
/Users/jayparekh/Documents/projects/musidict/src/components/data_loading.py:25: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  mfccs = torch.tensor(self.features['mfccs'][idx], dtype=torch.float32).unsqueeze(0)
/Users/jayparekh/Documents/projects/musidict/src/components/data_loading.py:26: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather

in forward torch.Size([2, 1, 128, 937])
in forward torch.Size([2, 3])
in forward torch.Size([1, 1, 128, 937])
in forward torch.Size([1, 3])
val_loss_mean 1.1453207731246948
train_loss_mean 0.9554255604743958
in forward torch.Size([1, 1, 128, 937])
in forward torch.Size([1, 3])


Seed set to 7
Seed set to 7
/Users/jayparekh/Documents/projects/musidict/src/components/data_loading.py:24: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  mel_spectrogram = torch.tensor(self.features['mel_spectrogram'][idx], dtype=torch.float32).unsqueeze(0)
/Users/jayparekh/Documents/projects/musidict/src/components/data_loading.py:25: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  mfccs = torch.tensor(self.features['mfccs'][idx], dtype=torch.float32).unsqueeze(0)
/Users/jayparekh/Documents/projects/musidict/src/components/data_loading.py:26: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_

Validation: |          | 0/? [00:00<?, ?it/s]

Seed set to 7
/Users/jayparekh/Documents/projects/musidict/src/components/data_loading.py:24: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  mel_spectrogram = torch.tensor(self.features['mel_spectrogram'][idx], dtype=torch.float32).unsqueeze(0)
/Users/jayparekh/Documents/projects/musidict/src/components/data_loading.py:25: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  mfccs = torch.tensor(self.features['mfccs'][idx], dtype=torch.float32).unsqueeze(0)
/Users/jayparekh/Documents/projects/musidict/src/components/data_loading.py:26: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather

in forward torch.Size([2, 1, 128, 937])
in forward torch.Size([2, 3])
in forward torch.Size([1, 1, 128, 937])
in forward torch.Size([1, 3])
val_loss_mean 1.1823062896728516
train_loss_mean 0.9439792633056641
in forward torch.Size([1, 1, 128, 937])
in forward torch.Size([1, 3])


Seed set to 7
Seed set to 7
Seed set to 7
/Users/jayparekh/Documents/projects/musidict/src/components/data_loading.py:24: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  mel_spectrogram = torch.tensor(self.features['mel_spectrogram'][idx], dtype=torch.float32).unsqueeze(0)
/Users/jayparekh/Documents/projects/musidict/src/components/data_loading.py:25: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  mfccs = torch.tensor(self.features['mfccs'][idx], dtype=torch.float32).unsqueeze(0)
/Users/jayparekh/Documents/projects/musidict/src/components/data_loading.py:26: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().

Validation: |          | 0/? [00:00<?, ?it/s]

in forward torch.Size([2, 1, 128, 937])
in forward torch.Size([2, 3])
in forward torch.Size([1, 1, 128, 937])
in forward torch.Size([1, 3])
val_loss_mean 1.2425323724746704
train_loss_mean 0.8669912219047546


Seed set to 7
Seed set to 7
/Users/jayparekh/Documents/projects/musidict/src/components/data_loading.py:24: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  mel_spectrogram = torch.tensor(self.features['mel_spectrogram'][idx], dtype=torch.float32).unsqueeze(0)
/Users/jayparekh/Documents/projects/musidict/src/components/data_loading.py:25: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  mfccs = torch.tensor(self.features['mfccs'][idx], dtype=torch.float32).unsqueeze(0)
/Users/jayparekh/Documents/projects/musidict/src/components/data_loading.py:26: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_

in forward torch.Size([1, 1, 128, 937])
in forward torch.Size([1, 3])


Seed set to 7
Seed set to 7
/Users/jayparekh/Documents/projects/musidict/src/components/data_loading.py:24: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  mel_spectrogram = torch.tensor(self.features['mel_spectrogram'][idx], dtype=torch.float32).unsqueeze(0)
/Users/jayparekh/Documents/projects/musidict/src/components/data_loading.py:25: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  mfccs = torch.tensor(self.features['mfccs'][idx], dtype=torch.float32).unsqueeze(0)
/Users/jayparekh/Documents/projects/musidict/src/components/data_loading.py:26: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_

Validation: |          | 0/? [00:00<?, ?it/s]

Seed set to 7
Seed set to 7
/Users/jayparekh/Documents/projects/musidict/src/components/data_loading.py:24: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  mel_spectrogram = torch.tensor(self.features['mel_spectrogram'][idx], dtype=torch.float32).unsqueeze(0)
/Users/jayparekh/Documents/projects/musidict/src/components/data_loading.py:25: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  mfccs = torch.tensor(self.features['mfccs'][idx], dtype=torch.float32).unsqueeze(0)
/Users/jayparekh/Documents/projects/musidict/src/components/data_loading.py:26: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_

in forward torch.Size([2, 1, 128, 937])
in forward torch.Size([2, 3])
in forward torch.Size([1, 1, 128, 937])
in forward torch.Size([1, 3])
val_loss_mean 1.272841453552246
train_loss_mean 0.7874878644943237


Seed set to 7
Seed set to 7
Seed set to 7
/Users/jayparekh/Documents/projects/musidict/src/components/data_loading.py:24: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  mel_spectrogram = torch.tensor(self.features['mel_spectrogram'][idx], dtype=torch.float32).unsqueeze(0)
/Users/jayparekh/Documents/projects/musidict/src/components/data_loading.py:25: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  mfccs = torch.tensor(self.features['mfccs'][idx], dtype=torch.float32).unsqueeze(0)
/Users/jayparekh/Documents/projects/musidict/src/components/data_loading.py:26: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().

in forward torch.Size([1, 1, 128, 937])
in forward torch.Size([1, 3])


Validation: |          | 0/? [00:00<?, ?it/s]

in forward torch.Size([2, 1, 128, 937])
in forward torch.Size([2, 3])
in forward torch.Size([1, 1, 128, 937])
in forward torch.Size([1, 3])
val_loss_mean 1.3046523332595825
train_loss_mean 0.8117021918296814


Seed set to 7
Seed set to 7
Seed set to 7
/Users/jayparekh/Documents/projects/musidict/src/components/data_loading.py:24: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  mel_spectrogram = torch.tensor(self.features['mel_spectrogram'][idx], dtype=torch.float32).unsqueeze(0)
/Users/jayparekh/Documents/projects/musidict/src/components/data_loading.py:25: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  mfccs = torch.tensor(self.features['mfccs'][idx], dtype=torch.float32).unsqueeze(0)
/Users/jayparekh/Documents/projects/musidict/src/components/data_loading.py:26: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().

in forward torch.Size([1, 1, 128, 937])
in forward torch.Size([1, 3])


Seed set to 7
Seed set to 7
Seed set to 7
/Users/jayparekh/Documents/projects/musidict/src/components/data_loading.py:24: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  mel_spectrogram = torch.tensor(self.features['mel_spectrogram'][idx], dtype=torch.float32).unsqueeze(0)
/Users/jayparekh/Documents/projects/musidict/src/components/data_loading.py:25: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  mfccs = torch.tensor(self.features['mfccs'][idx], dtype=torch.float32).unsqueeze(0)
/Users/jayparekh/Documents/projects/musidict/src/components/data_loading.py:26: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().

Validation: |          | 0/? [00:00<?, ?it/s]

Seed set to 7
/Users/jayparekh/Documents/projects/musidict/src/components/data_loading.py:24: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  mel_spectrogram = torch.tensor(self.features['mel_spectrogram'][idx], dtype=torch.float32).unsqueeze(0)
/Users/jayparekh/Documents/projects/musidict/src/components/data_loading.py:25: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  mfccs = torch.tensor(self.features['mfccs'][idx], dtype=torch.float32).unsqueeze(0)
/Users/jayparekh/Documents/projects/musidict/src/components/data_loading.py:26: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather

in forward torch.Size([2, 1, 128, 937])
in forward torch.Size([2, 3])
in forward torch.Size([1, 1, 128, 937])
in forward torch.Size([1, 3])
val_loss_mean 1.3586795330047607
train_loss_mean 0.7182735800743103


Seed set to 7
Seed set to 7
Seed set to 7
/Users/jayparekh/Documents/projects/musidict/src/components/data_loading.py:24: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  mel_spectrogram = torch.tensor(self.features['mel_spectrogram'][idx], dtype=torch.float32).unsqueeze(0)
/Users/jayparekh/Documents/projects/musidict/src/components/data_loading.py:25: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  mfccs = torch.tensor(self.features['mfccs'][idx], dtype=torch.float32).unsqueeze(0)
/Users/jayparekh/Documents/projects/musidict/src/components/data_loading.py:26: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().

in forward torch.Size([1, 1, 128, 937])
in forward torch.Size([1, 3])


Validation: |          | 0/? [00:00<?, ?it/s]

Seed set to 7
Seed set to 7
Seed set to 7
/Users/jayparekh/Documents/projects/musidict/src/components/data_loading.py:24: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  mel_spectrogram = torch.tensor(self.features['mel_spectrogram'][idx], dtype=torch.float32).unsqueeze(0)
/Users/jayparekh/Documents/projects/musidict/src/components/data_loading.py:24: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  mel_spectrogram = torch.tensor(self.features['mel_spectrogram'][idx], dtype=torch.float32).unsqueeze(0)
/Users/jayparekh/Documents/projects/musidict/src/components/data_loading.py:25: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTens

in forward torch.Size([2, 1, 128, 937])
in forward torch.Size([2, 3])
in forward torch.Size([1, 1, 128, 937])
in forward torch.Size([1, 3])
val_loss_mean 1.3994390964508057


INFO: `Trainer.fit` stopped: `max_epochs=10` reached.


train_loss_mean 0.7182298898696899


In [770]:
t_dash["mfccs"].shape

torch.Size([8, 13, 937])

In [777]:
t_dash["mfccs"][0].shape

torch.Size([1, 13, 937])

In [774]:
t_dash["mfccs"][0].unsqueeze(0).shape

torch.Size([1, 13, 937])

In [792]:
data_ingestion.DataIngestion().initiate_data_ingestion()

CustomException: Error occured in python script name [/Users/jayparekh/Documents/projects/musidict/src/components/data_ingestion.py] line number [32] error message[[Errno 2] No such file or directory: '/Users/jayparekh/Documents/projects/musidict/notebooks/data/raw_data']

In [800]:
a = ["ara", 1 , np.array([[1, 2], [2, 3]])]
b = [1 , np.array([[1, 2], [2, 3]])]

In [801]:
rows = [a, b]

In [802]:
d =np.stack(rows)

/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/numpy/core/shape_base.py:420: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arrays = [asanyarray(arr) for arr in arrays]


ValueError: all input arrays must have the same shape

In [797]:
d.shape

(2, 3)

In [805]:
import os
dataset = []
# logging.info("Data Ingestion Started.")
for filename in os.listdir("../data/raw_data"):
    data_point = []
    if filename.endswith('.npz'):
        file_path = os.path.join("../data/raw_data", filename)
        data = np.load(file_path, allow_pickle=True)
        genre = utils.preprocess_genres(data["metadata"][0]["genres"])
        if not genre:
            continue
        data_point.append(genre)
        data_point.append(data["metadata"][0]["bit_rate"])
        data_point.append(data["metadata"][0]["duration"])
        data_point.append(utils.categorize_listens(data["metadata"][0]["listens"]))
        

        data = utils.reshape_all_time_series_data(data)
        data_point.append(data["mel_spectrogram"])
        data_point.append(data["mfccs"])
        data_point.append(data["chroma"])
        data_point.append(data["spectral_contrast"])
        data_point.append(data["zcr"])
        data_point.append(data["spectral_centroid"])
        data_point.append(data["spectral_bandwidth"])
        data_point.append(data["rms_energy"])
        data_point.append(data["tonnetz"])
        print(data_point)
    dataset.append(data_point)
print(len(dataset))
dataset = np.stack(dataset)
print(dataset.shape)
dataset_df = pd.DataFrame(dataset, columns=[
    "genre",
    "bit_rate",
    "duration",
    "success",
    "mel_spectrogram",
    "mfccs",
    "chroma",
    "spectral_contrast",
    "zcr",
    "spectral_centroid",
    "spectral_bandwidth",
    "rms_energy",
    "tonnetz",
    ])

[38, 128000, 355, 'flop', array([[1.03552407e-02, 1.05597568e+00, 2.58046341e+01, ...,
        2.47676730e+00, 2.12609529e+00, 5.28111553e+00],
       [4.10787053e-02, 4.37608290e+00, 7.12891617e+01, ...,
        4.93570757e+00, 4.96458673e+00, 4.66866446e+00],
       [1.00170895e-01, 5.59270744e+01, 4.32613770e+02, ...,
        3.28476357e+00, 8.50086212e+00, 3.10108299e+01],
       ...,
       [3.34260730e-09, 2.09914560e-06, 6.87678994e-06, ...,
        4.88747730e-07, 1.91294771e-06, 7.15842121e-04],
       [3.05994785e-09, 2.40482404e-06, 7.78680896e-06, ...,
        9.56171107e-07, 2.39137194e-06, 8.42617301e-04],
       [3.30360461e-10, 5.75901247e-08, 1.59125605e-07, ...,
        4.24937170e-08, 1.92204357e-06, 7.80823291e-04]], dtype=float32), array([[-397.7112   , -180.10654  , -116.095955 , ..., -198.47946  ,
        -202.59973  , -130.7721   ],
       [ 110.92423  ,  201.9638   ,  217.11244  , ...,  204.52847  ,
         210.6015   ,  168.4455   ],
       [  12.104034 ,  -4

/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/numpy/core/shape_base.py:420: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arrays = [asanyarray(arr) for arr in arrays]
